imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.project_dir%/app/config/routing_admin.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }
