# To get started with security, check out the documentation:
# https://symfony.com/doc/current/security.html
security:
    encoders:
        FOS\UserBundle\Model\UserInterface: sha512

    role_hierarchy:
        ROLE_CONTRIBUTOR:  ROLE_USER
        ROLE_MANAGER:     [ROLE_USER, ROLE_CONTRIBUTOR]
        ROLE_ADMIN:       [ROLE_USER, ROLE_CONTRIBUTOR, ROLE_MANAGER]
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_CONTRIBUTOR, ROLE_MANAGER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    # https://symfony.com/doc/current/security.html#b-configuring-how-users-are-loaded
    providers:
        fos_userbundle:
            id: fos_user.user_provider.username
        in_memory:
            memory: ~

    firewalls:
        main:
            pattern: ^/
            form_login:
                provider: fos_userbundle
                csrf_token_generator: security.csrf.token_manager
                use_referer: true
            logout:
                path: /logout
                target: /admin
            anonymous: true
            logout_on_user_change: true
        dev:
            pattern: ^/(_(profiler|wdt)|css|images|js)/
            security: false
        default:
            anonymous: ~
            logout_on_user_change: true

    access_control:
        #- { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY, requires_channel: https }
        - { path: ^/login$, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/register, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/resetting, role: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/admin$, role: ROLE_CONTRIBUTOR }
        - { path: ^/admin/, role: ROLE_CONTRIBUTOR }
        - { path: ^/app_admin.php/admin$, role: ROLE_CONTRIBUTOR }
        - { path: ^/app_admin.php/admin/, role: ROLE_CONTRIBUTOR }
