eureka_g6k_fields:
    path:     /{simu}/Default/fields
    defaults: { _controller: EUREKAG6KBundle:Default:fields }

eureka_g6k_source:
    path:     /{simu}/Default/source
    defaults: { _controller: EUREKAG6KBundle:Default:source }

eureka_g6k_calcul:
    path:     /{simu}
    defaults: { _controller: EUREKAG6KBundle:Default:calcul }

eureka_g6k_calcul_view:
    path:     /{simu}/{view}
    defaults: { _controller: EUREKAG6KBundle:Default:calcul }

