parameters:

services:
    kernel.listener.g6k_exception_listener:
        class: EUREKA\G6KBundle\EventListener\G6KExceptionListener
        arguments: [ @service_container ]
        tags:
            - { name: kernel.event_listener, event: kernel.exception, method: onKernelException }

    g6k.file_uploader:
        class: EUREKA\G6KBundle\Services\FileUploader
        arguments: ['%g6k_upload_directory%']

    # TwigExtensions
    g6k.twig.filters_extension:
        class: EUREKA\G6KBundle\Twig\Extension\Filters
        tags:
            - { name: twig.extension }